receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: 0.0.0.0:14268

exporters:
  logging:

service:
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [logging]
  extensions: [zpages]

extensions:
  zpages: